# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MTIyZWQ5MTJkMTY1MDc4Y2ZjZWM0ODIxZmQ2MjNmZjgyZDNkM2NiZmZjZjU3YTU5NWMwNzIwNzk0OWVmODhhYzZhODMxZGRiN2YxYTI0MzlhN2MyMDkyYzg3OTY3ZGVlNjMyM2RiYTdkZjFiYzE5ZDdiZDEyNzk0YjdiMjM1MTQ=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
